### ISSUE TITLE
Error: No symbol named passive found

### ISSUE THREAD

**Issue by podhrmic** [seL4/rust-microkit-demo#3]
When compiling a dummy crate, such as:

```rust
#[protection_domain]
fn init() -> ThisHandler {
    todo!()
}
```

I get the following error:
```
...
Traceback (most recent call last):
  File "runpy", line 197, in _run_module_as_main
  File "runpy", line 87, in _run_code
  File "sel4coreplat.__main__", line 1782, in <module>
  File "sel4coreplat.__main__", line 1633, in main
  File "sel4coreplat.__main__", line 1507, in build_system
  File "sel4coreplat.elf", line 412, in write_symbol
  File "sel4coreplat.elf", line 442, in find_symbol
KeyError: 'No symbol named passive found'
```

The solution is obvious:
```rust
#[protection_domain]
fn init() -> ThisHandler {
    ThisHandler{}
}
```

It is a caveat that could surprise a new user. Not sure how to best tell the user that `todo!()` or `unimplemented!()` macros in the `init()` function are bad ideas, or even better improve the error message so it is clear how to fix this error?

**Comment by nspin** [comment]
Thanks for bringing this up! I found a solution using `#[used(linker)]`. This attribute ensures that a marked symbol appears in the binary even if it is not used.

Fixed in https://github.com/coliasgroup/rust-seL4/commit/00da7b5d0450d87a012a8c1ff0f5194370215330

**Comment by nspin** [comment]
Applied to this demo with https://github.com/coliasgroup/rust-seL4-sel4cp-demo/commit/bfbbdcb59bebfe34e854feea9bd97e1bdcd175e7

**Comment by nspin** [comment]
Added support for using a similar solution to cases involving `memory_region!()` in https://github.com/coliasgroup/rust-seL4/commit/92a473a85d0ee911bc5725c09f471138046dfb27
